### ISSUE TITLE
Cannot read property '@global' of undefined

### ISSUE THREAD

**Issue by eddielisands** [ErikDakoda/vulcan-material-ui#16]
I got the TypeError: Cannot read property '@global' of undefined at handleNestedGlobalContainerRule (node_modules/jss-global/lib/index.js:125:20) after upgrading the package from 1.10.1_9 to 1.11.2.

I followed those steps to install the npm modules and the error is still there.
$ meteor add erikdakoda:vulcan-material-ui

$ meteor npm install --save @material-ui/core
$ meteor npm install --save mdi-material-ui
$ meteor npm install --save react-autosuggest
$ meteor npm install --save autosuggest-highlight

**Comment by bin4ryio** [comment]
+1.

**Comment by eric-burel** [comment]
Related issue: https://github.com/mui-org/material-ui/issues/8652
I am also looking for a fix

**Comment by eddielisands** [comment]
Yes, the issue is from the "Components.AccountsLoginForm", I don't get the error if I commented that component out.

**Comment by eddielisands** [comment]
Tested with the latest update and it was fixed 👍
