### ISSUE TITLE
ThemeStyles.jsx Component Typographies

### ISSUE THREAD

**Issue by Apollinaire** [ErikDakoda/vulcan-material-ui#2]
All the typographies in the ThemeStyles component are passed a prop 'type' for their styling, I believe the prop should be "variant" instead?  From my point of view the typographies are displaying as the default "body1". 
See typography API here: https://material-ui-next.com/api/typography/
Or did you implement  a usage for this prop especially? 
@ErikDakoda

**Comment by ErikDakoda** [comment]
That's a change in the material-ui api that happened in just the past week. material-ui is still in beta and the API is still in flux. I suggest that you lock your project to v1.0.0-beta.31 by removing the ^ before the version number in your package.json:

    "material-ui": "1.0.0-beta.31",

I will continue to update this package to keep it in line with the latest version, but there might be a few weeks of lag time.
