### ISSUE TITLE
Sample theme not loaded

### ISSUE THREAD

**Issue by eric-burel** [ErikDakoda/vulcan-material-ui#29]
Hi, the Sample theme does not seem to be loaded automatically in the current version, not sure why, so `theme.utils` is undefined.

**Comment by kw7oe** [comment]
It seems that we have to import in our `lib/modules/index.js` file, as shown here:

https://github.com/ErikDakoda/vulcan-material-ui/blob/master/modules/index.js

Basically, is to include

```js
import './sampleTheme';
```
into our `lib/modules/index.js`

**Comment by eric-burel** [comment]
Hi @ErikDakoda , I've managed to setup a custom theme correctly indeed, it works fine (thanks again for this work). I did not try lately but here the issue was about the default theme, it was not registered automatically. I am going to close this because I think I just did not set import correctly at that time.
