### ISSUE TITLE
Something wrong with delete button's tooltip in FormSubmit component

### ISSUE THREAD

**Issue by michbak** [ErikDakoda/vulcan-material-ui#31]
See the attached picture. Tested with 1.11.2_1 and Material UI 3.2.2, but it looks the same with 3.0.3.
![image](https://user-images.githubusercontent.com/329442/47047118-0f31f800-d197-11e8-930b-4ab138f0aab8.png)

**Comment by ErikDakoda** [comment]
Thanks for the report, I just fixed it in version 1.12.8_4
