### ISSUE TITLE
Accounts forms: no labels neither placeholders (except with Chromium browser)

### ISSUE THREAD

**Issue by Julien-Sytadelle** [ErikDakoda/vulcan-material-ui#45]
Hi Erik,

There is a strange behavior of Accounts forms.
Except with Chromium browser, there are no labels, placeholders or even text inside buttons (spans are empty).
Login form with Chrome or Firefox:
![image](https://user-images.githubusercontent.com/32358941/49387153-6d07a880-f721-11e8-8b1a-a1cb403b4a7b.png)

Using Chromium:
![image](https://user-images.githubusercontent.com/32358941/49387214-932d4880-f721-11e8-9fe4-92c3cd604efa.png)

Any idea about this ?

Julien

**Comment by ErikDakoda** [comment]
What comes to mind is that in the problem browsers the language may be set to something other than English, and the required translation strings are not defined in that language.

**Comment by Julien-Sytadelle** [comment]
Hi,
Thanks for your quick reply. I will check this but i have chrome in english and firefox in french.
My app is only set in english but I will add french translation.
I just tried with a chrome profile without any extensions and it is working.
I close this issue and will comment if I find anything else than language.

**Comment by ErikDakoda** [comment]
I don't have tons of experience building multi-language sites yet, but you could also try adding the "vulcan-i18n-fr-fr" package to your project, if you haven't already.

**Comment by TroubadourFabiolas** [comment]
Hi @ErikDakoda , @Julien-Sytadelle 
I have had this same problem,
Its works on localhost but not on heroku remote server.

I added this env Variable : METEOR_SETTINGS={ "public": { "locale": "en" } }

And now it's good
