### ISSUE TITLE
Cannot find module 'autosize-input'

### ISSUE THREAD

**Issue by calinn** [ErikDakoda/vulcan-material-ui#49]
C:\Users\Calin\AppData\Local\.meteor\packages\meteor-tool\1.7.0_1\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280W20181214-12:43:50.177(-5)? (STDERR)                                            throw(ex);W20181214-12:43:50.178(-5)? (STDERR)                                            ^
W20181214-12:43:50.179(-5)? (STDERR)
W20181214-12:43:50.179(-5)? (STDERR) Error: Cannot find module 'autosize-input'
W20181214-12:43:50.179(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20181214-12:43:50.180(-5)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20181214-12:43:50.180(-5)? (STDERR)     at Object.require (C:\Users\Calin\Documents\proyectos\perros\perros\.meteor\local\build\programs\server\boot.js:288:32)
W20181214-12:43:50.180(-5)? (STDERR)     at makeInstallerOptions.fallback (packages\modules-runtime.js:618:18)
W20181214-12:43:50.181(-5)? (STDERR)     at Module.require (packages\modules-runtime.js:244:14)
W20181214-12:43:50.181(-5)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20181214-12:43:50.181(-5)? (STDERR)     at SearchInput.jsx (packages/erikdakoda:vulcan-material-ui/components/bonus/SearchInput.jsx:1:1115)
W20181214-12:43:50.181(-5)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20181214-12:43:50.182(-5)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20181214-12:43:50.182(-5)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20181214-12:43:50.182(-5)? (STDERR)     at index.js (packages/erikdakoda:vulcan-material-ui/components/index.js:1:429)
W20181214-12:43:50.183(-5)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20181214-12:43:50.183(-5)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20181214-12:43:50.184(-5)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20181214-12:43:50.184(-5)? (STDERR)     at main.js (packages/erikdakoda:vulcan-material-ui/server/main.js:1:14)
W20181214-12:43:50.184(-5)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20181214-12:43:50.184(-5)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20181214-12:43:50.185(-5)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20181214-12:43:50.185(-5)? (STDERR)     at C:\Users\Calin\Documents\proyectos\perros\perros\.meteor\local\build\programs\server\packages\erikdakoda_vulcan-material-ui.js:10238:15W20181214-12:43:50.185(-5)? (STDERR)     at C:\Users\Calin\Documents\proyectos\perros\perros\.meteor\local\build\programs\server\packages\erikdakoda_vulcan-material-ui.js:10243:3
W20181214-12:43:50.186(-5)? (STDERR)     at C:\Users\Calin\Documents\proyectos\perros\perros\.meteor\local\build\programs\server\boot.js:411:36
W20181214-12:43:50.189(-5)? (STDERR)     at Array.forEach (<anonymous>)
=> Exited with code: 1

**Comment by Apollinaire** [comment]
`meteor npm install autosize-input`
It has been introduced in `components/bonus/SearchInput.jsx`
We should add this to the readme

**Comment by Apollinaire** [comment]
See PR #50
