### ISSUE TITLE
 Cannot read property 'hocs' of undefined (/components/core/Datatable)

### ISSUE THREAD

**Issue by jacobpdq** [ErikDakoda/vulcan-material-ui#5]
Here's the error off of a fresh install:

at replaceComponent (packages/vulcan:lib/lib/modules/components.js:109:81)
at Datatable.jsx (packages/erikdakoda:vulcan-material-ui/components/core/Datatable.jsx:334:1)

Thanks for the great work!

**Comment by Apollinaire** [comment]
Looks like you're missing the vulcan:lib package. All the code here is an extension of Vulcan, it cannot work without it. You should clone https://github.com/VulcanJS/Vulcan , then add this package to it, with `meteor add erikdakoda:vulcan-material-ui`as said in the readme of the project.
