### ISSUE TITLE
Cannot find module '@material-ui/core/styles/createGenerateClassName'

### ISSUE THREAD

**Issue by iparrabb** [ErikDakoda/vulcan-material-ui#57]
Hi, 

I just installed this package following the README instructions but the app crashes with this error: Error: Cannot find module '@material-ui/core/styles/createGenerateClassName', any idea?

I'm working in a new Vulcan project, this is my package file:

```js
# see http://docs.vulcanjs.org/packages

vulcan:core

############ Language Packages ############

vulcan:i18n-en-us

############ Accounts Packages ############

accounts-password@1.5.1
# accounts-twitter
# accounts-facebook

############ Your Packages ############

# getting-started

# iparra-crud-posts
# example-simple
# example-movies
# example-instagram
# example-forum
# example-customization
# example-permissions
# example-membership
# example-interfaces
# example-reactions
# example-forms
tmeasday:check-npm-versions
erikdakoda:vulcan-material-ui
```

Thanks!

**Comment by ErikDakoda** [comment]
This package is no longer maintained because it has been rolled into the Vulcan project. In Vulcan 1.13.0+ you can `meteor add vulcan:ui-material`

**Comment by iparrabb** [comment]
Thanks @ErikDakoda, I solved it from the slack vulcan channel.
